[Feat] Portal 컴포넌트 추가
modorie/moida pull request #145
Opened 2022-09-10 10:56 UTC by devpla

## 📌 이슈

- close #144 

<br/>

## 📝 설명

- 재사용 가능하도록 포탈 컴포넌트를 만들었어요.
- 지금은 편의를 위해 스토리에 Portal을 씌워뒀지만, 모이다 앱 최상단에 Portal을 두면 좋을 것 같아요.

<br/>

## 📷 스크린샷

-

<br/>

2022-09-15 02:12 UTC, seokzin commented on components/Header/Header.stories.tsx
> +        {isNavbarOpened && <Navbar onClickClose={onClickClose} {...args} />}
이 코드 이슈는 아니지만 코드 컨벤션을 하나 제안할게요.
Spread를 프로퍼티로 주입할 때는 [오버라이드](https://stackoverflow.com/questions/59015798/does-order-matter-when-using-spread-syntax-in-react-component) 가능성을 고려하여 앞에 배치하는 것을 어떻게 생각하나요.

2022-09-15 02:15 UTC, seokzin commented on components/Modal/Modal.tsx
> -  if (!isModalOpen) return <></>
분기의 제거가 곧 책임의 제거죠.
이런 개선이 참 마음에 들어요 😊

2022-09-15 02:33 UTC, seokzin commented on components/Portal/Portal.tsx
> +    return el
리팩터링 원칙 중 '변수 인라인화'를 적용하는 것은 어떤가요?
지역변수 제거 및 return문 간소화의 효과가 있겠네요.
다만 DOM 생성이 비순수함수다보니 리팩터링시 주의해야겠어요.

```typescript
const [container] = useState(
  document.createElement(element).setAttribute('id', id)
)
```

2022-09-15 02:34 UTC, seokzin commented on components/Portal/Portal.types.ts
> +  id: `${string}-portal`
타입스크립트에서 string 타입도 any만큼 넓은 타입이죠.
템플릿 리터럴 타입 사용한 건 좋은 디테일이네요 👍

2022-09-15 02:35 UTC, seokzin requested changes
좋아요! 몇 가지 의견들 적어봤어요

2022-09-19 15:06 UTC, devpla commented on components/Header/Header.stories.tsx
> +        {isNavbarOpened && <Navbar onClickClose={onClickClose} {...args} />}
좋아요! 다만 불필요한 prop이 전달되지 않게 spread는 최대한 지양하는게 어떨까 싶어요!

2022-09-19 15:17 UTC, devpla commented on components/Portal/Portal.tsx
> +    return el
@seokzin 
저렇게 처리하면 `.setAttribute('id', id)`로 인해 container가 `void` 타입이 되어버려서 appendChild에 넣을 수 없어요.

![image](https://user-images.githubusercontent.com/87457066/191051240-e448e75a-ea25-4ff9-87fc-945460922983.png)

id 값을 넣지 않는다면 유효하겠지만

```tsx
const [container] = useState(document.createElement(element))
```

용도의 분리를 위해 id값을 입력해 주는 것이 좋아보입니다. 🤔

2022-09-19 15:39 UTC, seokzin commented on components/Header/Header.stories.tsx
> +        {isNavbarOpened && <Navbar onClickClose={onClickClose} {...args} />}
완전 찬성이에요. 최소한의 프로퍼티만 제어하도록 해요!

2022-09-19 15:47 UTC, seokzin commented on components/Portal/Portal.tsx
> +    return el
setAttribute가 리턴 값이 없어서 체이닝 결과가 void가 되는군요..
로컬에서 한 번 시도해보고 제안해볼걸 그랬어요. 😥
임시 변수를 사용하는 것이 최선이네요.

2022-09-20 15:39 UTC, seokzin approved these changes

2022-09-20 16:19 UTC, merged