[Feat] Calendar 컴포넌트 구현
modorie/moida pull request #160
Opened 2022-10-11 07:57 UTC by seokzin

## 📌 이슈

- close #159 

<br/>

## 📝 설명

- Calendar 컴포넌트를 구현해요.

<br/>

## 📷 스크린샷

-

<br/>

2022-10-30 14:52 UTC, YoonBaek reviewed
LGTM!

2022-10-30 15:36 UTC, devpla requested changes

2022-10-30 15:36 UTC, devpla commented on components/Calendar/Calendar.tsx
> +}
이 컴포넌트의 구조가 조금 고민돼요.
나중에 비즈니스 로직을 짜거나 api 통신을 할 때 `selected` 혹은 `handleSelected`를 Calendar 컴포넌트 외부에서 사용할 것으로 보여요.

저라면 `useCalendar`를 Calendar 컴포넌트 내부 말고, `.stories`에서 호출하면서 필요한 변수들을 prop으로 가져올 것 같아요 🤔

2022-10-30 15:36 UTC, devpla commented on components/Calendar/Calendar.styled.ts
> +  }
사소한 UX인데요.
selected된 직후에 hover 효과가 그대로 유지돼서, 순간적으로 selected가 되었는지 모르겠는 느낌이 있어요! hover일때 selected도 고려해주시면 좋을 것 같아요.

2022-10-30 15:36 UTC, devpla commented on components/Calendar/CalendarBody/CalendarBody.styled.ts
> +`
컴포넌트 분리하는 과정에서 `Calendar.styled`와 `CalendarBody.styled`에 중복된 코드가 있는 것 같아요!  😳

(+ `CalendarHeader.styled`에도 있네요!)

2022-10-30 15:36 UTC, devpla commented on utils/chunk.ts
> +export default chunk
이 유틸 너무 좋아요! 아이디어네요!! 👍
다만 함수 이름이 조금 더 명확했으면 좋겠어요. size를 이용해서 array를 chunk한다는 느낌이 더 드러나게?! 그리고 JSDoc도 추가해주시면 더 좋을 것 같아요.

2022-10-30 15:36 UTC, devpla commented on utils/generateCalendar.ts
>   */
JSDoc을 사용할 때 @returns, @param 등의 decorator를 써보는 거 어때요? 🤔

2022-10-31 00:09 UTC, seokzin commented on components/Calendar/Calendar.styled.ts
> +  }
좋은 디테일이네요..!
다행히 green200 색상이 남아서 이를 적용했어요.
(다만 색 조화가 조금 어색하긴 하네요. 추후 디자이너에게 AS 부탁해야겠어요. 😅)

2022-10-31 00:49 UTC, seokzin commented on components/Calendar/Calendar.tsx
> +}
음 저는 Calendar 내부에서 selected를 처리하는 로직을 고려했는데
여러 레퍼런스를 참고했을 때 onChange(selected)만 prop으로 넘기는 것이 일반적이네요.
위와 같은 구조로 변경을 진행해볼게요.

2022-10-31 00:52 UTC, seokzin commented on components/Calendar/CalendarBody/CalendarBody.styled.ts
> +`
저도 방금 코드를 보다가 발견했네요.
복제하는 과정에서 Lint가 잡아줄 거라 생각하고 신경 쓰지 않았네요.
앞으로 기존 파일을 복사하는 것보단 새로 만드는 방식을 습관화 해볼게요.

2022-10-31 01:01 UTC, seokzin commented on utils/chunk.ts
> +export default chunk
lodash의 [chunk](https://github.com/lodash/lodash/blob/master/chunk.js) 메서드를 참고했어요!
그래서 보편적인 네이밍은 유지하고 싶어요.

JSDoc은 유틸의 의도를 설명하기에 유용할 것 같아 추가했어요!
다만, TS의 함수 시그니처가 제공되기 때문에 타입 문서화는 생략했었어요.
(추가로 제 유틸들은 테스트 코드가 설명서 역할을 할 거예요. 😊)

2022-10-31 01:04 UTC, seokzin commented on utils/chunk.ts
> +export default chunk
lodash의 [chunk](https://github.com/lodash/lodash/blob/master/chunk.js) 메서드를 참고했어요!
그래서 보편적인 네이밍은 유지하고 싶어요.

JSDoc은 유틸의 의도를 설명하기에 유용할 것 같아 추가했어요!
다만, TS의 함수 시그니처가 제공되기 때문에 타입 문서화는 생략했었어요.
(추가로 제 유틸들은 테스트 코드가 설명서 역할을 할 거예요. 😊)

2022-10-31 01:36 UTC, seokzin commented on utils/generateCalendar.ts
>   */
마찬가지로 위와 같은 의견이에요.
추가로 유틸 함수에선 인터페이스보단 타입을 직접 명시하는 것이 사용하는 입장에서 많이 도움이 되네요!

https://github.com/modorie/moida/blob/10413e3181888e45b55c9f21b1820716942d2b25/utils/generateCalendar.ts#L22-L28

2022-11-02 12:48 UTC, devpla commented on utils/chunk.ts
> +export default chunk
맞아요! 타입스크립트여서 JSDoc이 필수는 아니지만, 데코레이션을 쓰면 하이라이팅 덕분에 가독성이 더 좋아지더라구요. 그래서 제안드려봤어요!

2022-11-02 12:48 UTC, devpla approved these changes

2022-11-02 13:57 UTC, merged