[Feat] Input 컴포넌트 사용성 개선, clear 기능 추가
modorie/moida pull request #163
Opened 2022-10-14 17:21 UTC by devpla

## 📌 이슈

- close #

<br/>

## 📝 설명

- controls 사용 편의성을 위해 rightContent prop으로 변경했어요. 
- useRef가 자주 쓰일 것이므로 forwardRef를 적용해두었어요. (아마 대부분의 컴포넌트에 이 작업이 필요할 것 같아요!)
- controls에 포함되어있던 clear 아이콘을 별도로 빼서, clear 기능을 외부 로직 없이 사용할 수 있도록 변경했어요.

<br/>

## 📷 스크린샷

-

<br/>

2022-10-16 09:59 UTC, devpla commented on components/Input/Input.tsx
> +  }, [activeClear])
input clear를 내부적으로 구현한 코드예요!

2022-10-16 10:03 UTC, devpla commented on utils/makeCombineRefs.ts
> +  }
컴포넌트 내부 ref와 forwardRef가 모두 필요한 상황에서 해당 ref들을 결합해주는 유틸이에요.

2022-10-17 00:03 UTC, seokzin commented on types/ComponentProps.ts
> +  onClick?: (e: React.MouseEvent) => void
```
onClick?: (e?: React.MouseEvent) => void
```
onClick 함수의 이벤트 프로퍼티는 옵셔널하게 선언하는 것이 맞는 듯 해요!

2022-10-17 00:18 UTC, seokzin commented on components/Input/Input.tsx
> +  const combineRefs = makeCombineRefs<HTMLInputElement>(inputRef, forwardedRef)
`makeCombineRefs`의 리턴 값이 void인데 변수에 할당해도 괜찮았나요?

2022-10-17 00:44 UTC, seokzin commented on components/Input/Input.tsx
> +  }, [activeClear])
setValue는 세터 역할을 하는 것인가요?
혹시 로직을 짤 때 참고한 레퍼런스가 있을까요?
코드를 이해하는 데 도움 받고 싶어서요!

2022-10-17 00:51 UTC, seokzin requested changes
clear 로직이나 combineRef 로직이 흥미로웠어요.
물어보고 싶은 게 있어서 나중에 코드 리뷰 시간을 따로 갖고 싶어요.
추가로 타입 정의를 다시 확인 해봐야겠어요.

2022-10-24 14:33 UTC, devpla commented on components/Input/Input.tsx
> +  }, [activeClear])
예전에 구글링하다 발견해서 잘 쓰고있던 코드예요! 검색해봤지만 원본 레퍼런스가 어디있는지 모르겠네요.
그나마 찾은 비슷한 코드는 [여기](https://gist.github.com/slavrinja/e8996c628c243b80326e4c228d731b29#file-set_input_value-js-L17) 있어요. 참고해주세요!

clear 버튼을 누를 때 그냥 `inputRef.current.value = ''` 와 같이 처리하면, change event로 감지되지 않아요.
그래서 clear 기능의 커스텀 이벤트를 만들어서, input 내부 로직에 주입했다 정도로 이해하면 될 것 같아요.

2022-10-24 14:37 UTC, devpla commented on components/Input/Input.tsx
> +  const combineRefs = makeCombineRefs<HTMLInputElement>(inputRef, forwardedRef)
![image](https://user-images.githubusercontent.com/87457066/197552490-1e695bfb-6d85-4f4b-b8c1-8c38395ad327.png)
ref가 refObject도 받지만 함수도 받을 수 있어요!

2022-10-26 00:57 UTC, seokzin commented on components/Input/Input.tsx
> +  const combineRefs = makeCombineRefs<HTMLInputElement>(inputRef, forwardedRef)
헉 VS에서 직접 고차 함수인 걸 확인 해 놓고 undefined라 말했네요 🥺
다음부턴 조금 더 꼼꼼한 리뷰어가 될게요!
ref에 함수를 할당할 수 있는 방법에 대해서는 새롭게 알았어요!

2022-10-26 01:00 UTC, seokzin commented on components/Input/Input.tsx
> +  }, [activeClear])
커스텀 이벤트 주입을 통해 change를 감지하게 만드는 사실은 몰랐던 이슈네요.
아직은 낯선 Input 로직에 대해 많이 배워가요!

2022-10-26 01:02 UTC, seokzin commented on utils/makeCombineRefs.ts
> +  }
유용한 기능의 유틸이에요. 코드도 재밌구요.
직접 써보고 싶어지네요.

2022-10-26 01:02 UTC, seokzin approved these changes

2022-10-30 08:55 UTC, merged